version: 2
jobs:
  python27: &test-template
    docker:
      - image: circleci/python:2.7
    environment:
      TOXENV: py27
    steps:
      - checkout
      - run: pip install --user tox
      - run: /home/circleci/.local/bin/tox

  python34:
    <<: *test-template
    docker:
      - image: circleci/python:3.4
    environment:
      TOXENV: py34

  python35:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35

  python36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36

  python37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37

  flake8:
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: flake8
    steps:
      - checkout
      - run: pip install --user tox
      - run: /home/circleci/.local/bin/tox

  build:
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: build
    steps:
      - checkout
      - run: pip install --user tox
      - run: /home/circleci/.local/bin/tox
      - store_artifacts:
          path: dist
          destination: packages

workflows:
  version: 2
  test-and-build:
    jobs:
      - flake8:
          filters:
            tags:
              only: /^v.*/
      - python27:
          filters:
            tags:
              only: /^v.*/
      - python34:
          filters:
            tags:
              only: /^v.*/
      - python35:
          filters:
            tags:
              only: /^v.*/
      - python36:
          filters:
            tags:
              only: /^v.*/
      - python37:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - flake8
            - python27
            - python34
            - python35
            - python36
            - python37
          filters:
            tags:
              only: /^v.*/
